extends: existence
message: Avoid directional instructions and any language that requires someone to see the layout or design of the page. Consider removing '%s'
link: "https://docs.google.com/document/d/1kT8423WTLIRHZC-5wQuu3_fuiNqqmDQ7zny7f4VqBPA/edit#heading=h.gdht13fnonmq"
scope: sentence
ignorecase: true
level: suggestion
tokens: 
    - left
    - right
    - center
    - top
    - bottom

