extends: existence
message: Avoid directional instructions and any language that requires someone to see the layout or design of the page. Consider removing '%s'
link: ""
scope: sentence
ignorecase: true
level: warning
tokens: 
    - left
    - right
    - center
    - top
    - bottom

