extends: substitution
message: Use gender neutral language when possible. Consider using '%s' instead of '%s'
link: ""
level: error
ignorecase: true
# swap maps tokens in form of bad: good
swap:
    he: they
    she: they