extends: existence
message: "Form a negative number with an en dash, not a hyphen."
link: https://docs.google.com/document/d/1kT8423WTLIRHZC-5wQuu3_fuiNqqmDQ7zny7f4VqBPA/edit#heading=h.1kgierejkqve
nonword: true
level: warning
tokens:
  - '\s-\d+\s'