extends: existence
message: "Spell out all ordinal numbers ('%s') in text."
link: 'https://docs.google.com/document/d/1kT8423WTLIRHZC-5wQuu3_fuiNqqmDQ7zny7f4VqBPA/edit#heading=h.13vtqerosmt2'
level: error
nonword: true
tokens:
  - \d+(?:st|th|rd|nd|ly)