extends: existence
message: United States telephone number should have the format (xxx)-xxx-xxxx '%s'
link: "https://docs.google.com/document/d/1kT8423WTLIRHZC-5wQuu3_fuiNqqmDQ7zny7f4VqBPA/edit#heading=h.ycicvkhncjnh"
ignorecase: true
nonword: true
level: warning
tokens: 
    - (?:\d\d\d-\d\d\d-\d\d\d\d)