name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: ./ # Uses an action in the root directory
      with:
        styles: |
          https://github.com/tperry-r7/ux-writing-linter/archive/v1.1.zip
        config:
          https://raw.githubusercontent.com/tperry-r7/ux-writing-linter/master/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
